export type User = {
  id: number;
  profile_id: number;
  name: string;
  login_name: string;
  role: 'admin' | 'teacher' | 'student';
  grade: number | null;
  must_change_password: boolean;
};
export type LoginUsers = { students: User[]; teachers: User[] };
export type Subject = { id: number; name: string; grade: number; hours_per_week: number; hours_per_year: number; source_info: string | null; instruction_language?: 'ru' | 'ky'; progress?: number };
export type Section = { id: number; subject_id: number; name: string; sort_order: number; total_hours: number };
export type LessonType = 'study' | 'review' | 'assessment' | 'reflection' | 'project';
export type Topic = { subject_id?: number; covered_topic_ids?: number[]; source_assessment_topic_id?: number | null; archived_at?: string | null; review_required?: boolean; id: number; section_id: number; ktp_number: string | null; name: string; hours: number; lesson_type: string; learning_objectives: string | null; skills: string[]; resources: string | null; lesson_id?: number | null; lesson_status?: 'draft' | 'published' | null };
export type KtpTopicDraft = {
  ktp_number: string;
  name: string;
  hours: number;
  lesson_type: LessonType;
  learning_objectives: string;
  skills: string[];
  resources: string;
  note?: string;
  confidence?: 'high' | 'low';
};
export type KtpSectionDraft = { name: string; total_hours: number; topics: KtpTopicDraft[] };
export type KtpDraft = {
  subject_name: string;
  grade: number;
  hours_per_week: number;
  hours_per_year: number;
  instruction_language: 'ru' | 'ky';
  sections: KtpSectionDraft[];
  warnings?: string[];
  source?: { filename: string; kind: string; table_count: number; row_count: number };
  stats?: { section_count: number; topic_count: number; low_confidence_count: number; with_objectives: number };
};
export type SectionOutline = Section & { topics: Topic[] };
export type LearningObjective = {
  id: string;
  text: string;
  success_criteria?: string;
};
export type ObjectiveEvidence = {
  objective_id: string;
  block_index?: number;
  stage?: 'diagnostic' | 'explanation' | 'practice' | 'assessment' | string;
  correct?: boolean;
  score?: number;
  attempts?: number;
};
export type MasteryStatus = 'not_assessed' | 'in_progress' | 'mastered' | 'needs_practice';
export type ObjectiveMastery = {
  status: MasteryStatus;
  score?: number;
  diagnostic_passed?: boolean;
  final_passed?: boolean;
};
export type QualityReport = {
  publishable?: boolean;
  objectives?: Record<string, {
    objective?: string;
    diagnostic?: number[];
    explanation?: number[];
    practice?: number[];
    assessment?: number[];
    evidence?: Array<{ block: number; stage: string }>;
  }>;
  gaps?: Array<{ objective_id?: string; objective?: string; missing?: string[] } | string>;
  errors?: Array<{ code?: string; block?: number; message?: string } | string>;
  warnings?: Array<{ code?: string; block?: number; message?: string } | string>;
  legacy?: boolean;
};
export type ObjectiveResult = {
  status: MasteryStatus;
  score?: number;
  evidence?: ObjectiveEvidence[];
};
export type WarpGate = {
  from_topic_id: number;
  to_topic_id: number;
  topic_name: string;
  subject_name: string;
  readiness_score: number;
  explanation: string;
  trigger_skill_ids: number[];
};
export type ProgressRecord = { responses?: Record<string, string>; topic_name?: string; archived_at?: string | null; id: number; student_id: number; topic_id: number; status: 'not_started' | 'in_progress' | 'completed'; score: number | null; mastery_level: string | null; mastery_status?: MasteryStatus; objective_mastery?: Record<string, ObjectiveMastery>; objective_evidence?: Record<string, ObjectiveEvidence[]>; time_spent_sec: number; attempts: number; current_step: number; max_opened_step: number; answers: Record<string, boolean>; attempts_by_step: Record<string, number>; elapsed_time_sec: number; lesson_version_id?: number | null; current_episode_id?: string | null; current_scene_id?: string | null; avatar_enabled?: boolean; audio_enabled?: boolean; updated_at?: string | null; warp_gates?: WarpGate[]; };
export type CurriculumTopicState = 'locked' | 'available' | 'in_progress' | 'mastered';
export type CurriculumMapTopic = {
  lesson_type?: LessonType;
  covered_topic_ids?: number[];
  source_assessment_topic_id?: number | null;
  progress_status?: "not_started" | "in_progress" | "completed";
  id: number;
  name: string;
  hours: number;
  section_id: number;
  section_name: string;
  subject_id: number;
  subject_name: string;
  grade: number;
  state: CurriculumTopicState;
  readiness_score: number;
  reason: string;
  unlocked_by_topic_id: number | null;
  lesson_status: 'published' | 'preparing';
  mastery_status: MasteryStatus | null;
  attempts: number;
};
export type CurriculumMap = { student_id: number; topics: CurriculumMapTopic[] };
export type CurriculumGraphSkill = { id: number; name: string; role: 'prerequisite' | 'outcome' | 'transfer' };
export type CurriculumGraphTopic = { lesson_type?: LessonType; covered_topic_ids?: number[]; source_assessment_topic_id?: number | null; id: number; name: string; section: string; objectives: string | null; skills: CurriculumGraphSkill[] };
export type CurriculumGraphEdge = { id: number; from_topic_id: number; to_topic_id: number; relation: 'prerequisite' | 'progression' | 'transfer' | 'cross_subject'; confidence: number; rationale: string };
export type CurriculumGraph = {
  subject: { id: number; name: string; grade: number };
  topics: CurriculumGraphTopic[];
  edges: CurriculumGraphEdge[];
  cross_subject_opportunities: Array<{
    from_topic_id: number;
    from_topic_name: string;
    from_subject_name: string;
    to_topic_id: number;
    to_topic_name: string;
    to_subject_name: string;
    confidence: number;
    rationale: string;
  }>;
};
export type DashboardOverview = { students: number; subjects: number; topics: number; published_lessons: number; average_progress: number };
export type StudentSummary = { id: number; name: string; grade: number; completed_topics: number; average_score: number };
export type ComponentSchema = {
  type?: string;
  enum?: string[];
  required?: string[];
  minItems?: number;
  maxItems?: number;
  properties?: Record<string, ComponentSchema>;
  items?: ComponentSchema;
};
export type ComponentRegistryEntry = {
  id: string;
  code: string;
  category: string;
  subjects: string[];
  purpose: string;
  is_assessment: boolean;
  content_schema: ComponentSchema;
  rendering_notes: string;
  roles?: string[];
  cognitive_actions?: string[];
  heavy_engine?: boolean;
  best_for_volume?: string[];
};
export type Block = {
  component: string;
  content: Record<string, unknown>;
};
export type AvatarCue = {
  id: string;
  scene_id?: string;
  beat_id?: string;
  slide_id?: string;
  phase: 'intro' | 'explain' | 'prompt' | 'hint' | 'feedback' | 'recap' | string;
  role?: 'explain' | 'focus' | 'analogy' | 'prompt' | 'feedback' | string;
  script: string;
  short_script?: string;
  trigger: 'scene_start' | 'student_request' | 'correct_answer' | 'first_error' | 'repeated_error' | 'inactivity' | string;
  fallback_text: string;
  audio_asset_id?: number;
  video_asset_id?: number;
  audio_url?: string;
  video_url?: string;
  poster_url?: string;
  autoplay?: boolean;
};
export type AvatarCueAsset = {
  id: number;
  video_url: string;
  poster_url?: string | null;
  duration_ms?: number | null;
  mime_type?: string | null;
  scene_id?: string | null;
  cue_id?: string | null;
  beat_id?: string | null;
};
export type LessonAsset = {
  id: number;
  kind: string;
  url: string;
  mime_type?: string;
  duration_ms?: number;
  poster_url?: string;
  scene_id?: string;
  beat_id?: string;
  slide_id?: string;
  cue_id?: string;
  pedagogical_role?: string;
  placement?: string;
};
export type TeachingBeat = {
  id: string;
  objective_ids: string[];
  title: string;
  learning_point?: string;
  avatar_cue_ids: string[];
  media_slot_ids: string[];
};
export type LessonScene = {
  id: string;
  original_block_index?: number;
  purpose: 'orient' | 'activate' | 'explain' | 'investigate' | 'practice' | 'assess' | 'reflect' | string;
  title: string;
  objective_ids: string[];
  block: Block;
  teaching_beats?: TeachingBeat[];
  avatar_cues: AvatarCue[];
  assets?: LessonAsset[];
  completion_rule: 'viewed' | 'interaction' | 'correct_answer';
};
export type LessonEpisode = {
  id: string;
  title: string;
  phase: string;
  objective_ids: string[];
  estimated_minutes: number;
  scenes: LessonScene[];
};
export type LessonDocument = {
  schema_version: 2;
  source?: string;
  title: string;
  format: string;
  estimated_minutes: number;
  objectives: LearningObjective[];
  episodes: LessonEpisode[];
  avatar: {
    enabled: boolean;
    mode: 'scripted' | 'live_optional' | string;
    language: 'ru' | 'ky' | string;
    profile_id?: number;
    profile_name?: string;
    preview_image_url?: string | null;
  };
};
export type EducationalImageRequest = {
  lesson_version_id?: number;
  scene_id?: string;
  block_id?: string;
  beat_id?: string;
  slide_id?: string;
  media_slot_id?: string;
  placement?: string;
  topic: string;
  subject?: string;
  grade?: number;
  concept?: string;
  learning_goal?: string;
  visual_form?: string;
  visual_intent?: string;
  pedagogical_role?: string;
  misconception_to_avoid?: string;
  curriculum_context?: string;
  source_context?: string;
  must_include?: string[];
  avoid?: string[];
  success_check?: string;
  prompt?: string;
  style?: string;
  labels_language?: string;
  aspect_ratio?: string;
  resolution?: string;
  quality?: string;
  output_format?: 'png' | 'jpeg' | 'webp';
  model?: string;
};
export type EducationalImageResponse = {
  kind: 'image';
  model: string;
  prompt: string;
  media_type: string;
  b64_json: string;
  data_url: string;
  url?: string;
  usage?: Record<string, unknown>;
};
export type EducationalVideoRequest = {
  lesson_version_id?: number;
  scene_id?: string;
  block_id?: string;
  beat_id?: string;
  slide_id?: string;
  media_slot_id?: string;
  placement?: string;
  topic: string;
  subject?: string;
  grade?: number;
  concept?: string;
  learning_goal?: string;
  visual_form?: string;
  visual_intent?: string;
  pedagogical_role?: string;
  misconception_to_avoid?: string;
  curriculum_context?: string;
  source_context?: string;
  must_include?: string[];
  avoid?: string[];
  success_check?: string;
  prompt?: string;
  style?: string;
  labels_language?: string;
  aspect_ratio?: string;
  duration?: number;
  resolution?: string;
  generate_audio?: boolean;
  model?: string;
};
export type EducationalVideoResponse = {
  kind: 'video';
  id: string;
  status: string;
  model: string;
  polling_url?: string;
  generation_id?: string;
  generation_job_id?: number;
  unsigned_urls?: string[];
  content_url?: string;
  usage?: Record<string, unknown>;
  error?: Record<string, unknown> | null;
  prompt?: string;
};
export type MediaRecommendation = {
  id: string;
  kind: 'image' | 'video';
  title: string;
  reason: string;
  subject_family: string;
  block_index: number;
  slide_index?: number | null;
  scene_id?: string;
  beat_id?: string;
  slide_id?: string;
  heading: string;
  learning_goal: string;
  source_context: string;
  visual_intent: string;
  visual_form: string;
  pedagogical_role: string;
  style: string;
  visual_system?: string;
  must_include: string[];
  avoid: string[];
  success_check: string;
  placement: 'slide_visual' | 'after_block';
  component: string;
  priority: number;
};
export type LessonMediaPlan = {
  subject: string;
  topic: string;
  subject_family: string;
  strategy: string;
  visual_system?: string;
  recommendations: MediaRecommendation[];
};
export type BlockMediaPlan = Omit<LessonMediaPlan, 'strategy'>;
export type GeneratedLesson = {
  id: number;
  topic_id: number;
  blocks: Block[];
  lesson_metadata: Record<string, unknown> & {
    objectives?: LearningObjective[];
    quality_report?: QualityReport;
    legacy_review_required?: boolean;
    topic_contract?: TopicContract;
    lesson_shape?: string;
    block_budget?: BlockBudget;
    component_plan?: ComponentPlanStep[];
  };
  status: 'draft' | 'published';
  generated_at: string;
  published_at: string | null;
  published_by: number | null;
  model_used: string | null;
  active_version_id?: number | null;
  published_version_id?: number | null;
  has_unpublished_changes?: boolean;
  lesson_document?: LessonDocument;
};

export type StudentLessonManifest = {
  lesson: GeneratedLesson;
  progress: ProgressRecord | null;
};
export type AvatarProfile = {
  id: number;
  name: string;
  provider: string;
  provider_avatar_id: string;
  provider_voice_id?: string | null;
  supported_languages: string[];
  voice_settings: Record<string, unknown>;
  consent_metadata?: Record<string, unknown>;
  preview_image_url?: string | null;
  preview_audio_url?: string | null;
  is_active: boolean;
};
export type AvatarCatalogItem = Record<string, unknown> & {
  id?: string;
  avatar_id?: string;
  voice_id?: string;
  avatar_name?: string;
  name?: string;
  display_name?: string;
  preview_image_url?: string;
  preview_audio_url?: string;
  preview_audio?: string;
  audio_url?: string;
  preview_video_url?: string;
  gender?: string;
  language?: string;
  locale?: string;
  type?: string;
};
export type AvatarGenerationJob = {
  id: number;
  lesson_version_id: number;
  scene_id?: string | null;
  status: 'queued' | 'submitted' | 'processing' | 'completed' | 'failed' | string;
  external_job_id?: string | null;
  request_payload?: Record<string, unknown>;
  result_payload?: Record<string, unknown>;
  error?: Record<string, unknown> | null;
};

export type BlockBudget = {
  min?: number;
  max?: number;
  heavy_max?: number;
};

export type TopicContract = {
  topic_name?: string;
  subject_name?: string;
  grade?: number;
  hours?: number;
  lesson_type?: string;
  volume?: 'micro' | 'standard' | 'extended' | 'unit' | string;
  complexity?: 'low' | 'medium' | 'high' | string;
  objective_count?: number;
  learning_focus?: string;
  lesson_shape?: string;
  block_budget?: BlockBudget;
  media_policy?: 'disabled' | 'optional' | 'suggested' | string;
  module_part_index?: number;
  module_total_parts?: number;
  suggested_next_parts?: string[];
};

export type ComponentPlanStep = {
  role?: string;
  evidence_stage?: string | null;
  objective_ids?: string[];
  allowed_components?: string[];
  cognitive_action?: string;
  required?: boolean;
};
