import { useState } from 'react';
import { ArrowDown, ArrowRight, Check, MoveUpRight, Sprout } from 'lucide-react';
import { SquareModel } from './SquareModel';
import { GardenQuestion } from './GardenQuestion';
import { type GardenState, type QuestionId } from './model';

export const gardenImage = `${import.meta.env.BASE_URL}images/lessons/square-garden.png`;

function RootDiscovery() {
  const [reverse, setReverse] = useState(false);
  return <div className="garden-discovery"><span className="garden-eyebrow">ДВА НАПРАВЛЕНИЯ ОДНОЙ ИДЕИ</span><div className="garden-number-pair"><div><strong>{reverse ? '16' : '4'}</strong><span>{reverse ? 'площадь, м²' : 'сторона, м'}</span></div><ArrowRight /><div><strong>{reverse ? '4' : '16'}</strong><span>{reverse ? 'сторона, м' : 'площадь, м²'}</span></div></div><div className="garden-large-formula">{reverse ? '√16 = 4' : '4² = 4 × 4 = 16'}</div><p>{reverse ? 'Знаем площадь. Ищем неотрицательное число, которое при умножении на себя даст 16.' : 'Знаем сторону. Умножаем её на себя и получаем площадь.'}</p><button className="garden-secondary" onClick={() => setReverse(!reverse)}>{reverse ? 'От стороны к площади' : 'А если известна площадь?'} <MoveUpRight size={18} /></button></div>;
}

export function GardenScenes({ state, setSide, answer, go }: { state: GardenState; setSide: (side: number) => void; answer: (id: QuestionId, value: number) => void; go: (step: number) => void }) {
  const { step, side, responses } = state;
  const correct = Object.values(responses).filter(r => r.correct).length;
  if (step === 0) return <div className="garden-intro"><div className="garden-intro-copy"><span className="garden-eyebrow"><Sprout size={16} /> МАТЕМАТИКА, КОТОРУЮ ВИДНО</span><h1>Большая идея.<br /><em>Квадратный сад.</em></h1><p>У тебя есть участок, немного плитки и один вопрос: как превратить площадь в длину стороны?</p><p className="garden-intro-secondary">Построй. Измени. Проверь свою догадку.<br />Квадратные корни обретут смысл.</p><button className="garden-primary" onClick={() => go(1)}>Спроектировать сад <ArrowRight size={19} /></button><div className="garden-meta"><span>8 коротких сцен</span><span>В своём темпе</span><span>Без таймера</span></div></div><div className="garden-hero-art"><img src={gardenImage} alt="Миниатюрный квадратный сад с деревьями, дорожками и оранжереей" fetchPriority="high" /><div className="garden-art-label"><span>ТВОЙ БУДУЩИЙ ПРОЕКТ</span><strong>От первого квадрата — к открытию</strong></div></div></div>;
  if (step === 1) return <div className="garden-scene-grid"><div className="garden-copy"><span className="garden-eyebrow">01 / СОБЕРИ СВОЮ ИДЕЮ</span><h1>16 плиток.<br /><em>Один квадрат.</em></h1><p>Каждая плитка закрывает 1 м². Нужно уложить все 16 плиток в квадрат без пробелов.</p><div className="garden-instruction"><MoveUpRight size={22} /><p>Двигай ползунок. Найди сторону, при которой площадь станет <strong>16 м²</strong>.</p></div><p className="garden-note">В квадрате столько же рядов, сколько плиток в каждом ряду. Нажми «Выделить ряд», чтобы увидеть это.</p></div><SquareModel side={side} onSide={setSide} target={16} /></div>;
  if (step === 2) return <div className="garden-scene-grid"><div className="garden-copy"><span className="garden-eyebrow">02 / МОМЕНТ ОТКРЫТИЯ</span><h1>Корень — это<br /><em>обратный путь.</em></h1><p>Четыре ряда по четыре плитки дают 16 м². Мы можем пройти этот путь в обе стороны.</p><div className="garden-definition"><span>ВОТ ЧТО ЗНАЧИТ ЗНАК √</span><p><strong>√16 = 4</strong> читается: «квадратный корень из шестнадцати равен четырём».</p></div><p className="garden-note">√a — неотрицательное число, квадрат которого равен a. Например, √0 = 0. Здесь тренируемся на квадратах с целой стороной.</p></div><RootDiscovery /></div>;
  if (step === 3) return <div className="garden-scene-grid"><div className="garden-copy"><span className="garden-eyebrow">03 / МАЛЕНЬКАЯ ЛАБОРАТОРИЯ</span><h1>А если сад<br /><em>вырастет?</em></h1><p>Увеличь сторону с 3 до 6 метров. Как изменится площадь?</p><div className="garden-live-reading" aria-live="polite"><span>СТОРОНА → ПЛОЩАДЬ</span><strong>{side}² = {side * side}</strong><ArrowDown size={20} /><span>ПЛОЩАДЬ → СТОРОНА</span><strong>√{side * side} = {side}</strong></div><p className="garden-note">При увеличении стороны в 2 раза площадь растёт в 4 раза: 3² = 9, а 6² = 36. Меняется и число рядов, и число клеток в ряду.</p></div><SquareModel side={side} onSide={setSide} /></div>;
  if (step === 4 || step === 5 || step === 6) {
    const id = step === 4 ? 'predict' : step === 5 ? 'trap' : 'project';
    return <div className="garden-scene-grid"><div className="garden-copy"><span className="garden-eyebrow">0{step} / {step === 4 ? 'СНАЧАЛА ДОГАДКА' : step === 5 ? 'ОШИБКА — ЧАСТЬ ОТКРЫТИЯ' : 'ТЕПЕРЬ ТЫ АРХИТЕКТОР'}</span><h1>{step === 4 ? <>Предскажи.<br /><em>Потом проверь.</em></> : step === 5 ? <>Звучит логично.<br /><em>Но сходится ли?</em></> : <>Последний штрих.<br /><em>Твой чертёж.</em></>}</h1><GardenQuestion key={id} id={id} response={responses[id]} onAnswer={value => answer(id, value)} /></div><div className="garden-challenge-visual">{responses[id]?.correct ? <SquareModel side={step === 4 ? 5 : step === 5 ? 4 : 7} /> : <><div className="garden-blueprint"><span>ПЛАН КВАДРАТНОЙ ПЛОЩАДКИ</span><div className="garden-blueprint-square"><strong>{step === 4 ? '25' : step === 5 ? '16' : '49'}<small>м²</small></strong></div><p>← <b>?</b> м →</p></div><p className="garden-note">Площадь известна. Длина стороны пока спрятана.<br />Какое число в квадрате даст эту площадь?</p></>}</div></div>;
  }
  return <div className="garden-finish"><div><span className="garden-eyebrow"><Sprout size={18} /> {correct === 3 ? 'ПРОЕКТ ГОТОВ' : 'ТВОИ ОТКРЫТИЯ'}</span><h1>Теперь у корня<br /><em>есть смысл.</em></h1><p>Из стороны — в площадь. Из площади — обратно в сторону.</p><div className="garden-summary-equation">7 м <span>→ × 7 →</span> 49 м² <span>→ √ →</span> 7 м</div><h2>{correct} из 3 задач решены</h2><div className="garden-summary-list">{(['predict', 'trap', 'project'] as QuestionId[]).map((id, i) => <button key={id} onClick={() => go(i + 4)}><span>{responses[id]?.correct ? <Check size={19} /> : <ArrowRight size={19} />}{['Найти сторону по площади', 'Отличить корень от деления пополам', 'Самостоятельно проверить решение'][i]}</span><small>{responses[id]?.correct ? responses[id]?.tries === 1 ? 'С первой попытки' : 'После разбора' : 'Попробовать'}</small></button>)}</div><div className="garden-definition"><span>ВОПРОС НА ВЫРОСТ</span><p>А если площадь 20 м²? Целой стороны не получится, но корень существует: 4² &lt; 20 &lt; 5², значит <strong>4 &lt; √20 &lt; 5</strong>.</p></div><button className="garden-secondary" onClick={() => go(3)}>Вернуться в лабораторию <ArrowRight size={18} /></button></div><img src={gardenImage} alt="Готовый сад — результат твоего проекта" /></div>;
}
