import { useState } from 'react';
import { ArrowRight, Check, Compass, Droplets, Landmark, Search } from 'lucide-react';
import { SampleQuestion } from './SampleQuestion';
import type { SampleAnswer } from './sampleModel';
import { historyAreas, historyLesson, historySources } from './historyContent';
import './history.css';

const art = (name: string) => `${import.meta.env.BASE_URL}images/lessons/${name}`;

function HistoryArt({ market = false }: { market?: boolean }) {
  return <figure className="sample-art history-art"><img src={art(market ? 'karakhanid-market.png' : 'karakhanid-city.png')} alt={market ? 'Художественная сцена рынка: ткани, керамика и товары каравана' : 'Художественный образ города Центральной Азии с полями и караваном'} /><figcaption>Художественная реконструкция с помощью ИИ. Не историческое свидетельство.</figcaption></figure>;
}

function CityExplorer() {
  const [selected, setSelected] = useState(0);
  const area = historyAreas[selected];
  return <div className="sample-panel history-explorer">
    <div className="history-map">
      <img src={art('karakhanid-city.png')} alt="Условная панорама для изучения четырёх частей хозяйства" />
      {historyAreas.map((item, index) => <button key={item.name} type="button" style={{ left: `${item.x}%`, top: `${item.y}%` }} className="history-map-pin" aria-label={`Исследовать: ${item.name}`} aria-pressed={selected === index} onClick={() => setSelected(index)}><span aria-hidden="true">{item.icon}</span><b>{index + 1}</b></button>)}
    </div>
    <div className="history-area-buttons" aria-label="Части хозяйства">{historyAreas.map((item, index) => <button key={item.name} type="button" aria-pressed={selected === index} onClick={() => setSelected(index)}>{index + 1}. {item.name}</button>)}</div>
    <div className="history-area-copy" aria-live="polite"><span className="sample-eyebrow">{area.label}</span><h2>{area.link}</h2><p>{area.detail}</p></div>
    <p className="sample-note">Точки обозначают учебные разделы. Это условная схема, а не план конкретного средневекового города.</p>
  </div>;
}

function WaterModel() {
  const [blocked, setBlocked] = useState(false);
  return <div className="sample-panel history-water"><span className="sample-eyebrow">МОДЕЛЬ ПРИЧИН И СЛЕДСТВИЙ</span><div className={`history-water-track ${blocked ? 'is-blocked' : ''}`}><Droplets size={42} /><div className="history-canal"><span /></div><span className="history-field" aria-hidden="true">🌾</span></div><button className="sample-primary" type="button" aria-pressed={blocked} onClick={() => setBlocked(!blocked)}>{blocked ? 'Очистить канал' : 'Что, если канал засорится?'}</button><p aria-live="polite">{blocked ? 'Полив нарушен. Растения получают меньше воды. Урожай может уменьшиться.' : 'Вода по каналу поступает к полям. Орошение помогает выращивать урожай.'}</p><p className="sample-note">Учебная модель: показывает одну связь. На урожай также влияют погода, почва и труд людей.</p></div>;
}

export function HistoryScenes({ step, answers, onAnswer }: { step: number; answers: Record<string, SampleAnswer>; onAnswer: (id: string, choice: number) => void }) {
  if (step === 0) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow"><Compass size={17} /> ИСТОРИЯ, В КОТОРУЮ МОЖНО ВОЙТИ</span><h1>За воротами —<br /><em>целый мир связей.</em></h1><p>Утро. К городу подходит караван. На базаре уже ждут зерно, ткани и посуду. Но откуда берётся всё это богатство?</p><p>Исследуй хозяйство эпохи Караханидов и выясни, почему городу нужны поля, стада, мастера и торговцы.</p><div className="sample-facts"><span>Центральная Азия</span><span>X–XII века</span><span>7 коротких сцен</span></div><p className="sample-note">Это собирательная учебная история. Персонажи и события дня придуманы для объяснения темы.</p></div><HistoryArt /></div>;
  if (step === 1) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">01 / ИССЛЕДУЙ ГОРОД</span><h1>Четыре занятия.<br /><em>Одна жизнь.</em></h1><p>Нажми на каждую точку. Узнай, что создают люди и кому нужен результат их труда.</p><p>Хозяйство — это производство и обмен тем, что нужно людям для жизни.</p><div className="history-prompt"><Search size={22} /><p>Найди связь между пастбищем и мастерской. Что может пройти этот путь?</p></div></div><CityExplorer /></div>;
  if (step === 2) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">02 / ПРОСЛЕДИ ПУТЬ ВЕЩИ</span><h1>Ткань начинается<br /><em>не на базаре.</em></h1><SampleQuestion id="chain" question={historyLesson.questions.chain} answer={answers.chain} onAnswer={choice => onAnswer('chain', choice)} /></div><div className="sample-panel history-chain"><span className="sample-eyebrow">ПУТЬ ШЕРСТИ В НАШЕЙ УЧЕБНОЙ ИСТОРИИ</span>{[['🐑', 'Стадо', 'Получить шерсть'], ['🧶', 'Мастерская', 'Обработать шерсть и изготовить ткань'], ['⚖️', 'Рынок', 'Предложить готовую ткань покупателям']].map(([icon, title, text], index) => <div key={title}><article><span aria-hidden="true">{icon}</span><section><h2>{title}</h2><p>{text}</p></section></article>{index < 2 && <ArrowRight className="history-chain-arrow" aria-hidden="true" />}</div>)}</div></div>;
  if (step === 3) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">03 / ПРОВЕРЬ СВЯЗЬ</span><h1>А если вода<br /><em>не дойдёт?</em></h1><p>Попробуй изменить одно условие в модели. Затем выбери самый обоснованный вывод.</p><SampleQuestion id="water" question={historyLesson.questions.water} answer={answers.water} onAnswer={choice => onAnswer('water', choice)} /></div><WaterModel /></div>;
  if (step === 4) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">04 / ДУМАЙ КАК ИСТОРИК</span><h1>Красивая история.<br /><em>А где доказательства?</em></h1><SampleQuestion id="evidence" question={historyLesson.questions.evidence} answer={answers.evidence} onAnswer={choice => onAnswer('evidence', choice)} /></div><div className="sample-panel history-evidence"><Landmark size={42} /><h2>Свидетельство → осторожный вывод</h2><div><strong>Находка</strong><p>Печь и бракованные сосуды в датированном археологическом слое.</p></div><div><strong>Вопрос исследователя</strong><p>Что здесь делали? Какие ещё находки помогут проверить догадку?</p></div><div><strong>Иллюстрация</strong><p>Помогает представить прошлое. Сама по себе не доказывает, как оно выглядело.</p></div><p className="sample-note">Пример находки условный. Источники к содержанию урока — в последней сцене.</p></div></div>;
  if (step === 5) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">05 / СОБЕРИ ОБЩУЮ КАРТИНУ</span><h1>Караван привёз<br /><em>не весь город.</em></h1><p>Дальняя торговля связывала разные местности. Но жизнь города опиралась и на труд людей рядом: земледельцев, скотоводов и ремесленников.</p><div className="history-prompt"><Compass size={24} /><p>Объясни своими словами: почему даже большой базар не мог заменить поля и мастерские?</p></div><details className="history-reveal"><summary>Сравнить с примером объяснения</summary><p>Рынок помогает обмениваться товарами. Чтобы появился товар, его сначала нужно вырастить или изготовить. Торговля связывает производство и потребление.</p></details><p className="sample-note">Шёлковые пути — сеть маршрутов. По ним перемещались разные товары, знания и технологии.</p></div><HistoryArt market /></div>;
  const solved = Object.entries(historyLesson.questions).filter(([id, question]) => answers[id]?.choice === question.correct).length;
  return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow"><Check size={18} /> ТВОИ ОТКРЫТИЯ</span><h1>Теперь ты видишь<br /><em>связи за вещами.</em></h1><p>Поля и стада дают пищу и сырьё. Мастера создают вещи. Торговля соединяет людей и местности.</p><h2>{solved} из 3 вопросов решены</h2><ul className="history-outcomes"><li>Различать земледелие, скотоводство, ремесло и торговлю.</li><li>Объяснять связь воды, урожая и снабжения города.</li><li>Отличать обоснованный вывод от догадки.</li></ul><p className="sample-note">Чтобы повторить вопрос, выбери его сцену в навигации урока.</p><details className="history-reveal"><summary>Источники и границы реконструкции</summary><p>Урок опирается на исследования. Изображения, схема города, история ткани и ситуация с каналом — учебные реконструкции.</p><ul>{historySources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label}</a></li>)}</ul></details></div><HistoryArt market /></div>;
}
