import { useState } from 'react';
import { ArrowRight, FlaskConical, Scale } from 'lucide-react';
import { SampleQuestion } from './SampleQuestion';
import { calculateDensity, densityToSI, physicsLesson } from './physicsContent';
import './physicsScenes.css';

const asset = (name: string) => `${import.meta.env.BASE_URL}images/lessons/${name}`;
const number = (value: number) => value.toLocaleString('ru-RU', { maximumFractionDigits: 2 });
type Response = { choice: number; tries: number };

function DensityLab() {
  const [mass, setMass] = useState(60);
  const [volume, setVolume] = useState(20);
  const density = calculateDensity(mass, volume);
  const size = 125 * Math.cbrt(volume / 20);
  return <div className="sample-panel physics-lab">
    <span className="sample-eyebrow">ЭКСПЕРИМЕНТ С ВЕЛИЧИНАМИ</span>
    <div className="physics-vessel" aria-hidden="true"><div className="physics-cube" style={{ width: size, height: size, opacity: 0.45 + density / 40 }}><span>{volume}<small>см³</small></span></div><div className="physics-balance">{mass} г</div></div>
    <div className="physics-controls">
      <label htmlFor="density-mass">Масса <strong>{mass} г</strong></label><input id="density-mass" type="range" min="10" max="180" step="10" value={mass} onChange={event => setMass(Number(event.target.value))} />
      <label htmlFor="density-volume">Объём <strong>{volume} см³</strong></label><input id="density-volume" type="range" min="10" max="60" step="10" value={volume} onChange={event => setVolume(Number(event.target.value))} />
    </div>
    <output className="physics-readout" aria-live="polite"><span>{mass} г ÷ {volume} см³</span><strong>{number(density)} <small>г/см³</small></strong><span>{number(densityToSI(density))} кг/м³</span></output>
    <p className="sample-note">Это модель со свободным выбором массы и объёма. Для одного однородного материала при одинаковых условиях их отношение постоянно.</p>
  </div>;
}

function Cubes() {
  return <div className="sample-panel physics-comparison"><span className="sample-eyebrow">ОДИНАКОВЫЙ ОБЪЁМ · РАЗНАЯ МАССА</span><div className="physics-pair">{[{ mass: 27, color: '#8ba4ad' }, { mass: 78, color: '#cb8653' }].map(({ mass, color }, index) => <div key={mass}><div className="physics-cube" style={{ backgroundColor: color }} aria-hidden="true"><span>10<small>см³</small></span></div><strong>{mass} г</strong><span>Кубик {index + 1}</span></div>)}</div><p className="sample-note">Размер не говорит нам, сколько массы находится внутри. Для сравнения нужна новая величина.</p></div>;
}

export function PhysicsScenes({ step, answers, onAnswer }: { step: number; answers: Record<string, Response>; onAnswer: (id: string, choice: number) => void }) {
  if (step === 0) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow"><FlaskConical size={16} /> ФИЗИКА · 7 КЛАСС · ПЛОТНОСТЬ</span><h1>У вещей есть<br /><em>скрытая мера.</em></h1><p>В мастерскую привезли два одинаковых кубика. Один легко лежит на ладони. Другой заметно тяжелее.</p><p>Размеры совпадают. Почему масса — нет?</p><div className="sample-facts"><span>Исследуй материал</span><span>Проведи опыт</span><span>Раскрой формулу</span></div><p className="sample-note">За семь сцен ты научишься сравнивать плотность, вычислять её и переводить единицы.</p></div><figure className="sample-art"><img src={asset('density-workshop.png')} alt="Иллюстрированная мастерская: весы, образцы материалов и измерительные инструменты" fetchPriority="high" /><figcaption>Твоя исследовательская мастерская</figcaption></figure></div>;
  if (step === 1) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">01 / СНАЧАЛА ПРЕДСКАЖИ</span><h1>Одинаковый размер.<br /><em>Разный характер.</em></h1><p>Плотность показывает, какая масса приходится на единицу объёма. Для начала сравним кубики без формулы.</p><SampleQuestion id="compare" question={physicsLesson.questions.compare} answer={answers.compare} onAnswer={choice => onAnswer('compare', choice)} /></div><Cubes /></div>;
  if (step === 2) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">02 / ПРОВЕРЬ СВОИ ДОГАДКИ</span><h1>Что изменится,<br /><em>если…</em></h1><p>В твоих руках масса и объём. Измени одно значение, оставив другое прежним. Наблюдай за плотностью.</p><ol className="physics-experiments"><li><strong>Удвой массу.</strong><span>При объёме 20 см³ сравни 60 и 120 г. Плотность тоже удвоится.</span></li><li><strong>Удвой объём.</strong><span>При массе 60 г сравни 20 и 40 см³. Плотность уменьшится вдвое.</span></li><li><strong>Удвой оба значения.</strong><span>Сравни 60 г / 20 см³ и 120 г / 40 см³. Отношение останется прежним.</span></li></ol></div><DensityLab /></div>;
  if (step === 3) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">03 / ИДЕЯ СТАНОВИТСЯ ФОРМУЛОЙ</span><h1>Масса на каждый<br /><em>кусочек объёма.</em></h1><p>Представь деталь объёмом 20 см³ и массой 60 г. Раздели массу поровну между двадцатью кубическими сантиметрами.</p><div className="physics-formula"><strong>ρ = m / V</strong><span>плотность = масса ÷ объём</span><p>60 г ÷ 20 см³ = <b>3 г/см³</b></p></div><p className="sample-note">ρ — греческая буква «ро». Если m измерена в граммах, а V — в см³, результат получается в г/см³.</p></div><figure className="sample-art"><img src={asset('density-closeup.png')} alt="Художественная иллюстрация образцов материалов и измерений в мастерской" /><figcaption>Числа берём из измерений, а иллюстрация помогает представить опыт.</figcaption></figure></div>;
  if (step === 4) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">04 / ТВОЁ ПЕРВОЕ ИЗМЕРЕНИЕ</span><h1>У детали нет этикетки.<br /><em>Есть измерения.</em></h1><p>Весы и измерение объёма уже дали всё необходимое. Найди массу одного кубического сантиметра.</p><SampleQuestion id="calculate" question={physicsLesson.questions.calculate} answer={answers.calculate} onAnswer={choice => onAnswer('calculate', choice)} /></div><div className="sample-panel physics-case"><Scale size={36} /><span className="sample-eyebrow">КАРТОЧКА ОБРАЗЦА № 07</span><div className="physics-measure"><span>МАССА</span><strong>54 <small>г</small></strong><ArrowRight /><span>ОБЪЁМ</span><strong>20 <small>см³</small></strong></div><div className="physics-formula"><strong>ρ = ?</strong><span>Сколько граммов в 1 см³?</span></div><p className="sample-note">По одной плотности не всегда можно однозначно определить материал. Здесь наша задача — вычислить величину.</p></div></div>;
  if (step === 5) return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">05 / ОДНА ПЛОТНОСТЬ, ДВЕ ЗАПИСИ</span><h1>Меняем единицы.<br /><em>Сохраняем смысл.</em></h1><p>В системе СИ массу измеряют в килограммах, объём — в кубических метрах. Поэтому единица плотности — кг/м³.</p><SampleQuestion id="units" question={physicsLesson.questions.units} answer={answers.units} onAnswer={choice => onAnswer('units', choice)} /></div><div className="sample-panel physics-conversion"><span className="sample-eyebrow">ОТ МАЛЕНЬКОГО К БОЛЬШОМУ</span><strong>1 г/см³</strong><span className="physics-equals">=</span><strong>1 000 кг/м³</strong><div className="physics-conversion-detail"><p>1 г = 0,001 кг</p><p>1 см³ = 0,000001 м³</p><p>0,001 ÷ 0,000001 = <b>1 000</b></p></div><p className="sample-note">Меняются сразу две единицы — и массы, и объёма. Поэтому учитываем оба преобразования.</p></div></div>;
  const correct = Object.entries(physicsLesson.questions).filter(([id, question]) => answers[id]?.choice === question.correct).length;
  return <div className="sample-grid"><div className="sample-copy"><span className="sample-eyebrow">06 / ТЕПЕРЬ ТЫ ВИДИШЬ БОЛЬШЕ</span><h1>Одинаковый размер —<br /><em>ещё не одинаковая масса.</em></h1><p>Ты нашёл скрытую меру: массу на единицу объёма.</p><div className="physics-formula"><strong>ρ = m / V</strong><span>Больше масса при том же объёме → больше плотность.</span></div><h2>{correct} из 3 задач решены</h2><p>Можешь вернуться к любой сцене через навигацию и проверить свои ответы ещё раз.</p><div className="sample-panel"><span className="sample-eyebrow">ВОПРОС ДЛЯ СЛЕДУЮЩЕГО ОТКРЫТИЯ</span><p>Если разрезать однородный кубик пополам, изменится ли плотность?</p><details><summary>Проверить рассуждение</summary><p>Нет: масса и объём каждой половины уменьшатся вдвое. Их отношение, а значит и плотность материала при тех же условиях, сохранится.</p></details></div></div><figure className="sample-art"><img src={asset('density-workshop.png')} alt="Мастерская, в которой теперь понятен смысл плотности" /><figcaption>Смотри на предметы. Замечай отношения.</figcaption></figure></div>;
}
