-- Lesson Experience v2: immutable lesson versions, provider jobs and media assets.
-- Existing lessons remain readable while the application migrates to lesson_document.

alter table public.generated_lessons
  alter column blocks type jsonb using blocks::jsonb,
  alter column lesson_metadata type jsonb using lesson_metadata::jsonb;

create table public.lesson_versions (
  id bigint generated by default as identity primary key,
  lesson_id integer not null references public.generated_lessons(id) on delete cascade,
  version_number integer not null check (version_number > 0),
  schema_version integer not null default 2 check (schema_version >= 1),
  status varchar(50) not null default 'draft'
    check (status in ('draft', 'generating', 'ready', 'published', 'failed', 'archived')),
  blueprint jsonb not null default '{}'::jsonb,
  lesson_document jsonb not null default '{}'::jsonb,
  generator_config jsonb not null default '{}'::jsonb,
  model_used varchar(255),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (lesson_id, version_number)
);

alter table public.generated_lessons add column active_version_id bigint;
alter table public.generated_lessons
  add constraint generated_lessons_active_version_fk
  foreign key (active_version_id) references public.lesson_versions(id) on delete set null;

create table public.avatar_profiles (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  provider varchar(50) not null default 'heygen',
  provider_avatar_id varchar(255) not null,
  provider_voice_id varchar(255),
  supported_languages text[] not null default array['ru']::text[],
  voice_settings jsonb not null default '{}'::jsonb,
  consent_metadata jsonb not null default '{}'::jsonb,
  preview_image_url text,
  preview_audio_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.generation_jobs (
  id bigint generated by default as identity primary key,
  lesson_version_id bigint not null references public.lesson_versions(id) on delete cascade,
  scene_id varchar(160),
  provider varchar(50) not null,
  job_type varchar(50) not null,
  external_job_id varchar(255),
  request_hash varchar(64) not null,
  status varchar(50) not null default 'queued'
    check (status in ('queued', 'submitted', 'processing', 'completed', 'failed', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  request_payload jsonb not null default '{}'::jsonb,
  result_payload jsonb not null default '{}'::jsonb,
  error jsonb,
  cost numeric(12, 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (provider, request_hash)
);

create table public.lesson_assets (
  id bigint generated by default as identity primary key,
  lesson_version_id bigint not null references public.lesson_versions(id) on delete cascade,
  generation_job_id bigint references public.generation_jobs(id) on delete set null,
  scene_id varchar(160),
  kind varchar(50) not null
    check (kind in ('image', 'video', 'audio', 'avatar_video', 'poster', 'document')),
  provider varchar(50) not null,
  provider_asset_id varchar(255),
  storage_bucket varchar(100),
  storage_path text,
  source_url text,
  mime_type varchar(150),
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  status varchar(50) not null default 'pending'
    check (status in ('pending', 'ready', 'failed', 'archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (lesson_version_id, scene_id, kind, provider_asset_id)
);

alter table public.progress
  add column lesson_version_id bigint references public.lesson_versions(id) on delete set null,
  add column current_episode_id varchar(160),
  add column current_scene_id varchar(160),
  add column avatar_enabled boolean not null default true,
  add column audio_enabled boolean not null default true,
  add column updated_at timestamptz not null default now();

create index lesson_versions_lesson_status_idx
  on public.lesson_versions (lesson_id, status, version_number desc);
create index generation_jobs_status_created_idx
  on public.generation_jobs (status, created_at);
create index generation_jobs_version_idx
  on public.generation_jobs (lesson_version_id);
create index lesson_assets_version_scene_idx
  on public.lesson_assets (lesson_version_id, scene_id);
create index progress_lesson_version_idx
  on public.progress (lesson_version_id) where lesson_version_id is not null;
create index sections_subject_sort_idx on public.sections (subject_id, sort_order);
create index topics_section_sort_idx on public.topics (section_id, sort_order);

insert into public.lesson_versions (
  lesson_id, version_number, schema_version, status, blueprint, lesson_document,
  generator_config, model_used, created_at, published_at
)
select
  gl.id,
  1,
  2,
  case when gl.status = 'published' then 'published' else 'ready' end,
  coalesce(gl.lesson_metadata, '{}'::jsonb),
  jsonb_build_object(
    'schema_version', 2,
    'source', 'legacy_blocks',
    'title', coalesce(gl.lesson_metadata->>'topic_name', 'Урок'),
    'estimated_minutes', greatest(5, coalesce((gl.lesson_metadata->'topic_contract'->>'hours')::integer, 1) * 20),
    'objectives', coalesce(gl.lesson_metadata->'objectives', '[]'::jsonb),
    'episodes', '[]'::jsonb,
    'legacy_blocks', coalesce(gl.blocks, '[]'::jsonb)
  ),
  jsonb_build_object('migrated_from', 'generated_lessons.blocks'),
  gl.model_used,
  gl.generated_at,
  gl.published_at
from public.generated_lessons gl
on conflict (lesson_id, version_number) do nothing;

update public.generated_lessons gl
set active_version_id = lv.id
from public.lesson_versions lv
where lv.lesson_id = gl.id and lv.version_number = 1 and gl.active_version_id is null;

update public.progress p
set lesson_version_id = gl.active_version_id
from public.generated_lessons gl
where gl.topic_id = p.topic_id and p.lesson_version_id is null;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('lesson-assets', 'lesson-assets', true, 104857600,
   array['image/png','image/jpeg','image/webp','image/svg+xml','video/mp4','video/webm','audio/mpeg','audio/wav']::text[]),
  ('lesson-drafts', 'lesson-drafts', false, 104857600,
   array['image/png','image/jpeg','image/webp','image/svg+xml','video/mp4','video/webm','audio/mpeg','audio/wav']::text[])
on conflict (id) do nothing;

-- The application uses a trusted backend connection. Keep the Data API closed
-- until Supabase Auth identities are mapped to the platform's student/teacher rows.
alter table public.subjects enable row level security;
alter table public.sections enable row level security;
alter table public.topics enable row level security;
alter table public.teachers enable row level security;
alter table public.students enable row level security;
alter table public.generated_lessons enable row level security;
alter table public.progress enable row level security;
alter table public.lesson_versions enable row level security;
alter table public.lesson_assets enable row level security;
alter table public.generation_jobs enable row level security;
alter table public.avatar_profiles enable row level security;

revoke all on table public.subjects, public.sections, public.topics,
  public.teachers, public.students, public.generated_lessons, public.progress,
  public.lesson_versions, public.lesson_assets, public.generation_jobs,
  public.avatar_profiles from anon, authenticated;

create policy "published lesson assets are readable"
on storage.objects for select to anon, authenticated
using (bucket_id = 'lesson-assets');
