-- Отзывы учеников в конце урока: оценка 1–5, были ли ошибки, комментарий. Всё необязательно.
-- Применяется владельцем: модель backend/feedback/models.py намеренно не входит в create_all при старте.
CREATE TABLE IF NOT EXISTS public.lesson_feedback (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id integer NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
 student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
 topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
 lesson_version_id bigint REFERENCES public.lesson_versions(id) ON DELETE SET NULL,
 rating smallint CHECK (rating BETWEEN 1 AND 5),
 had_errors boolean,
 comment text CHECK (char_length(comment) <= 2000),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS lesson_feedback_org_created_idx ON public.lesson_feedback(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS lesson_feedback_topic_idx ON public.lesson_feedback(topic_id);
ALTER TABLE public.lesson_feedback ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.lesson_feedback FROM anon, authenticated;
GRANT ALL ON public.lesson_feedback TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.lesson_feedback_id_seq TO service_role;
