-- Журнал реплик ИИ-тьютора. Применяется ТОЛЬКО после согласования владельцем:
-- модель backend/tutor/models.py намеренно не входит в create_all при старте.
-- Хранение: учебный год (очистка старых строк — отдельной задачей).
CREATE TABLE IF NOT EXISTS public.tutor_turns (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
 topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
 lesson_version_id bigint REFERENCES public.lesson_versions(id) ON DELETE SET NULL,
 block_index integer NOT NULL,
 question_index integer,
 step_index integer,
 event varchar(24) NOT NULL,
 student_text text,
 student_value varchar(200),
 check_outcome varchar(16),
 reply text NOT NULL DEFAULT '',
 reply_source varchar(12) NOT NULL,
 action varchar(24),
 action_args jsonb NOT NULL DEFAULT '{}',
 misconception_code varchar(80),
 diagnosis text,
 hint_level integer,
 safety_flag varchar(16) NOT NULL DEFAULT 'none',
 off_topic boolean NOT NULL DEFAULT false,
 leak_blocked boolean NOT NULL DEFAULT false,
 llm_called boolean NOT NULL DEFAULT false,
 provider varchar(80),
 model varchar(80),
 input_tokens integer,
 output_tokens integer,
 cache_read_tokens integer,
 cache_write_tokens integer,
 latency_ms integer,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tutor_turns_student_created_idx ON public.tutor_turns(student_id, created_at);
CREATE INDEX IF NOT EXISTS tutor_turns_student_block_idx ON public.tutor_turns(student_id, topic_id, block_index, created_at);
ALTER TABLE public.tutor_turns ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tutor_turns FROM anon, authenticated;
GRANT ALL ON public.tutor_turns TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.tutor_turns_id_seq TO service_role;
