-- Curriculum skill graph and explainable student warp gates.
-- The application currently writes through the trusted FastAPI backend. Public
-- Data API access stays closed until Supabase Auth identities are mapped.

create table public.skills (
  id bigint generated by default as identity primary key,
  canonical_key varchar(255) not null unique,
  name varchar(500) not null,
  normalized_name varchar(500) not null,
  subject_family varchar(80) not null default 'general',
  description text,
  grade_min integer not null default 7 check (grade_min between 1 and 12),
  grade_max integer not null default 10 check (grade_max between grade_min and 12),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.topic_skills (
  topic_id integer not null references public.topics(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  role varchar(30) not null check (role in ('prerequisite', 'outcome', 'transfer')),
  weight double precision not null default 1 check (weight > 0 and weight <= 1),
  mastery_threshold double precision not null default 0.8 check (mastery_threshold >= 0 and mastery_threshold <= 1),
  source varchar(40) not null default 'inferred',
  confidence double precision not null default 0.7 check (confidence >= 0 and confidence <= 1),
  objective_id varchar(160),
  created_at timestamptz not null default now(),
  primary key (topic_id, skill_id, role)
);

create table public.topic_edges (
  id bigint generated by default as identity primary key,
  from_topic_id integer not null references public.topics(id) on delete cascade,
  to_topic_id integer not null references public.topics(id) on delete cascade,
  relation varchar(30) not null check (relation in ('prerequisite', 'progression', 'transfer', 'cross_subject')),
  required_mastery double precision not null default 0.8 check (required_mastery >= 0 and required_mastery <= 1),
  confidence double precision not null default 0.7 check (confidence >= 0 and confidence <= 1),
  rationale text not null,
  source varchar(40) not null default 'inferred',
  created_at timestamptz not null default now(),
  check (from_topic_id <> to_topic_id),
  unique (from_topic_id, to_topic_id, relation)
);

create table public.student_skill_mastery (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  mastery_score double precision not null default 0 check (mastery_score >= 0 and mastery_score <= 1),
  status varchar(30) not null default 'emerging' check (status in ('emerging', 'developing', 'mastered')),
  evidence_count integer not null default 0 check (evidence_count >= 0),
  source_topic_id integer references public.topics(id) on delete set null,
  evidence jsonb not null default '{}'::jsonb,
  last_evidence_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (student_id, skill_id)
);

create table public.student_topic_access (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  topic_id integer not null references public.topics(id) on delete cascade,
  state varchar(30) not null default 'locked' check (state in ('locked', 'available', 'in_progress', 'mastered')),
  readiness_score double precision not null default 0 check (readiness_score >= 0 and readiness_score <= 1),
  reason text not null default '',
  unlocked_by_topic_id integer references public.topics(id) on delete set null,
  unlocked_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (student_id, topic_id)
);

create table public.warp_gate_events (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  from_topic_id integer not null references public.topics(id) on delete cascade,
  to_topic_id integer not null references public.topics(id) on delete cascade,
  readiness_score double precision not null check (readiness_score >= 0 and readiness_score <= 1),
  trigger_skill_ids bigint[] not null default '{}'::bigint[],
  explanation text not null,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  unique (student_id, from_topic_id, to_topic_id)
);

create index topic_skills_skill_role_idx on public.topic_skills (skill_id, role);
create index topic_edges_from_relation_idx on public.topic_edges (from_topic_id, relation);
create index topic_edges_to_relation_idx on public.topic_edges (to_topic_id, relation);
create index student_skill_mastery_student_status_idx on public.student_skill_mastery (student_id, status);
create index student_skill_mastery_skill_idx on public.student_skill_mastery (skill_id);
create index student_topic_access_student_state_idx on public.student_topic_access (student_id, state);
create index student_topic_access_topic_idx on public.student_topic_access (topic_id);
create index warp_gate_events_student_created_idx on public.warp_gate_events (student_id, created_at desc);
create index warp_gate_events_to_topic_idx on public.warp_gate_events (to_topic_id);

alter table public.skills enable row level security;
alter table public.topic_skills enable row level security;
alter table public.topic_edges enable row level security;
alter table public.student_skill_mastery enable row level security;
alter table public.student_topic_access enable row level security;
alter table public.warp_gate_events enable row level security;

revoke all on table public.skills, public.topic_skills, public.topic_edges,
  public.student_skill_mastery, public.student_topic_access,
  public.warp_gate_events from anon, authenticated;
