-- Beta identity model. Supabase Auth owns credentials; these tables own
-- platform roles, classroom scope and links to the existing learning history.

alter table public.students drop constraint if exists students_name_key;
alter table public.teachers drop constraint if exists teachers_name_key;

create table public.organizations (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(80) not null unique,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  role varchar(20) not null check (role in ('admin', 'teacher', 'student')),
  login_name varchar(100) not null,
  display_name varchar(255) not null,
  status varchar(20) not null default 'active'
    check (status in ('invited', 'active', 'blocked', 'archived')),
  must_change_password boolean not null default true,
  teacher_id integer unique references public.teachers(id) on delete set null,
  student_id integer unique references public.students(id) on delete set null,
  created_by_profile_id bigint references public.profiles(id) on delete set null,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, login_name),
  check ((role = 'teacher' and teacher_id is not null and student_id is null)
    or (role = 'student' and student_id is not null and teacher_id is null)
    or (role = 'admin' and teacher_id is null and student_id is null))
);

create table public.classrooms (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  name varchar(120) not null,
  grade integer not null check (grade between 1 and 12),
  academic_year varchar(20) not null,
  status varchar(20) not null default 'active'
    check (status in ('active', 'archived')),
  created_by_profile_id bigint references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, academic_year, name)
);

create table public.classroom_teachers (
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  teacher_id integer not null references public.teachers(id) on delete cascade,
  assigned_by_profile_id bigint references public.profiles(id) on delete set null,
  assigned_at timestamptz not null default now(),
  primary key (classroom_id, teacher_id)
);

create table public.classroom_students (
  id bigint generated by default as identity primary key,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  enrolled_by_profile_id bigint references public.profiles(id) on delete set null,
  enrolled_at timestamptz not null default now(),
  left_at timestamptz,
  unique (classroom_id, student_id)
);

create unique index classroom_students_one_active_class_idx
  on public.classroom_students (student_id) where left_at is null;
create index profiles_auth_status_idx on public.profiles (auth_user_id, status);
create index profiles_org_role_idx on public.profiles (organization_id, role, status);
create index classrooms_org_grade_idx on public.classrooms (organization_id, grade, status);
create index classroom_teachers_teacher_idx on public.classroom_teachers (teacher_id, classroom_id);
create index classroom_students_class_active_idx on public.classroom_students (classroom_id, student_id)
  where left_at is null;

create table public.account_events (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  actor_profile_id bigint references public.profiles(id) on delete set null,
  target_profile_id bigint references public.profiles(id) on delete set null,
  event_type varchar(50) not null check (event_type in (
    'account_created', 'password_reset_issued', 'password_changed',
    'account_blocked', 'account_restored', 'classroom_assigned', 'classroom_transferred'
  )),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index account_events_org_created_idx on public.account_events (organization_id, created_at desc);
create index account_events_target_created_idx on public.account_events (target_profile_id, created_at desc);

-- Security-definer helpers prevent recursive RLS evaluation while keeping all
-- authorization decisions anchored to the verified Supabase JWT identity.
create or replace function public.current_profile_id()
returns bigint language sql stable security definer set search_path = public
as $$ select id from public.profiles where auth_user_id = auth.uid() and status = 'active' limit 1 $$;

create or replace function public.current_profile_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.profiles where auth_user_id = auth.uid() and status = 'active' limit 1 $$;

create or replace function public.can_access_classroom(target_classroom_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$
  select case public.current_profile_role()
    when 'admin' then true
    when 'teacher' then exists (
      select 1 from public.classroom_teachers ct
      join public.profiles p on p.teacher_id = ct.teacher_id
      where ct.classroom_id = target_classroom_id and p.id = public.current_profile_id()
    )
    when 'student' then exists (
      select 1 from public.classroom_students cs
      join public.profiles p on p.student_id = cs.student_id
      where cs.classroom_id = target_classroom_id and cs.left_at is null
        and p.id = public.current_profile_id()
    )
    else false
  end
$$;

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.classrooms enable row level security;
alter table public.classroom_teachers enable row level security;
alter table public.classroom_students enable row level security;
alter table public.account_events enable row level security;

revoke all on public.organizations, public.profiles, public.classrooms,
  public.classroom_teachers, public.classroom_students, public.account_events
  from anon, authenticated;
grant select on public.organizations, public.profiles, public.classrooms,
  public.classroom_teachers, public.classroom_students to authenticated;

create policy "organization members can read organization"
on public.organizations for select to authenticated
using (id = (select organization_id from public.profiles where id = public.current_profile_id()));

create policy "profiles are scoped to self admin or assigned teacher"
on public.profiles for select to authenticated
using (
  id = public.current_profile_id()
  or public.current_profile_role() = 'admin'
  or (
    public.current_profile_role() = 'teacher' and role = 'student' and exists (
      select 1 from public.classroom_students cs
      join public.classroom_teachers ct on ct.classroom_id = cs.classroom_id
      join public.profiles viewer on viewer.teacher_id = ct.teacher_id
      where cs.student_id = profiles.student_id and cs.left_at is null
        and viewer.id = public.current_profile_id()
    )
  )
);

create policy "classrooms are visible to assigned members"
on public.classrooms for select to authenticated
using (public.can_access_classroom(id));

create policy "classroom teachers are visible to classroom members"
on public.classroom_teachers for select to authenticated
using (public.can_access_classroom(classroom_id));

create policy "classroom students are visible to classroom members"
on public.classroom_students for select to authenticated
using (public.can_access_classroom(classroom_id));

-- No client-side INSERT/UPDATE/DELETE policies are intentional. Account and
-- roster mutations are performed by FastAPI using the service role after RBAC.
