-- Preserve published content and completed results while introducing editable course structure.
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS covered_topic_ids jsonb NOT NULL DEFAULT '[]';
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS source_assessment_topic_id integer REFERENCES public.topics(id) ON DELETE SET NULL;
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS archived_at timestamptz;
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS review_required boolean NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS topics_active_section_sort_idx ON public.topics(section_id, sort_order) WHERE archived_at IS NULL;
ALTER TABLE public.generated_lessons ADD COLUMN IF NOT EXISTS published_version_id bigint REFERENCES public.lesson_versions(id) ON DELETE SET NULL;
UPDATE public.generated_lessons SET published_version_id = active_version_id
WHERE status = 'published' AND published_version_id IS NULL;
UPDATE public.progress p SET lesson_version_id=l.published_version_id
FROM public.generated_lessons l WHERE l.topic_id=p.topic_id AND p.lesson_version_id IS NULL;
ALTER TABLE public.progress ADD COLUMN IF NOT EXISTS responses jsonb NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS public.lesson_attempts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
 topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE RESTRICT,
 attempt_number integer NOT NULL,
 lesson_version_id bigint REFERENCES public.lesson_versions(id) ON DELETE RESTRICT,
 snapshot jsonb NOT NULL DEFAULT '{}',
 completed_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(student_id, topic_id, attempt_number)
);
ALTER TABLE public.lesson_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.lesson_attempts FROM anon, authenticated;
GRANT ALL ON public.lesson_attempts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.lesson_attempts_id_seq TO service_role;
INSERT INTO public.lesson_attempts(student_id, topic_id, attempt_number, lesson_version_id, snapshot, completed_at)
SELECT p.student_id, p.topic_id, greatest(1, coalesce(p.attempts,1)), p.lesson_version_id, to_jsonb(p), coalesce(p.completed_at,now())
FROM public.progress p WHERE p.status='completed'
ON CONFLICT(student_id, topic_id, attempt_number) DO NOTHING;
-- Specific purpose takes precedence over the word “контрольная”. Authored materials are untouched.
UPDATE public.topics SET lesson_type = CASE
 WHEN lower(name) ~ '(анализ|разбор).*контрольн|работа над ошибк' THEN 'reflection'
 WHEN lower(name) ~ 'повторени|ключевые идеи|пересмотр' THEN 'review'
 ELSE lesson_type END;
UPDATE public.topics t SET covered_topic_ids = coalesce((
 SELECT jsonb_agg(s.id ORDER BY s.sort_order,s.id) FROM public.topics s
 WHERE s.section_id=t.section_id AND (s.sort_order,s.id)<(t.sort_order,t.id)
 AND s.lesson_type IN ('study','project') AND s.archived_at IS NULL
),'[]'::jsonb), review_required=true
WHERE t.lesson_type IN ('assessment','review','reflection') AND t.covered_topic_ids='[]'::jsonb;
UPDATE public.topics t SET source_assessment_topic_id=(
 SELECT s.id FROM public.topics s WHERE s.section_id=t.section_id AND s.lesson_type='assessment'
 AND (s.sort_order,s.id)<(t.sort_order,t.id) ORDER BY s.sort_order DESC,s.id DESC LIMIT 1
) WHERE t.lesson_type='reflection' AND t.source_assessment_topic_id IS NULL;
-- Retain old evidence as history; remove only automatically inferred fictitious graph links.
DELETE FROM public.topic_skills ts USING public.skills s
WHERE ts.skill_id=s.id AND ts.source='inferred' AND s.name LIKE 'Освоение темы:%';
