-- Учебники как основа для ИИ. Применяется ТОЛЬКО после согласования владельцем:
-- модели backend/textbooks/models.py намеренно не входят в create_all при старте.
-- Сам PDF лежит в закрытой корзине Supabase Storage «textbooks», здесь — путь к нему.
CREATE TABLE IF NOT EXISTS public.textbooks (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id integer REFERENCES public.organizations(id) ON DELETE SET NULL,
 subject_id integer REFERENCES public.subjects(id) ON DELETE SET NULL,
 grade integer NOT NULL,
 language varchar(2) NOT NULL DEFAULT 'ru',
 title varchar(300) NOT NULL,
 authors varchar(300),
 year integer,
 storage_path text NOT NULL,
 file_size bigint,
 page_count integer,
 page_offset integer,
 student_display varchar(16) NOT NULL DEFAULT 'refs_only' CHECK (student_display IN ('refs_only', 'verbatim')),
 status varchar(20) NOT NULL DEFAULT 'uploaded',
 progress jsonb NOT NULL DEFAULT '{}',
 error text,
 created_by_profile_id integer,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS textbooks_subject_idx ON public.textbooks(subject_id, grade);

CREATE TABLE IF NOT EXISTS public.textbook_pages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 textbook_id bigint NOT NULL REFERENCES public.textbooks(id) ON DELETE CASCADE,
 page_index integer NOT NULL,
 printed_page integer,
 text text NOT NULL DEFAULT '',
 source varchar(8) NOT NULL DEFAULT 'text',
 status varchar(12) NOT NULL DEFAULT 'pending',
 needs_review boolean NOT NULL DEFAULT false,
 uncertain jsonb NOT NULL DEFAULT '[]',
 figures jsonb NOT NULL DEFAULT '[]',
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE (textbook_id, page_index)
);

CREATE TABLE IF NOT EXISTS public.textbook_sections (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 textbook_id bigint NOT NULL REFERENCES public.textbooks(id) ON DELETE CASCADE,
 position integer NOT NULL,
 number varchar(40) NOT NULL DEFAULT '',
 title text NOT NULL,
 chapter text NOT NULL DEFAULT '',
 printed_page integer,
 pdf_from integer NOT NULL,
 pdf_to integer NOT NULL,
 items_status varchar(12) NOT NULL DEFAULT 'pending'
);
CREATE INDEX IF NOT EXISTS textbook_sections_book_idx ON public.textbook_sections(textbook_id, position);

CREATE TABLE IF NOT EXISTS public.textbook_items (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 textbook_id bigint NOT NULL REFERENCES public.textbooks(id) ON DELETE CASCADE,
 section_id bigint NOT NULL REFERENCES public.textbook_sections(id) ON DELETE CASCADE,
 position integer NOT NULL,
 kind varchar(16) NOT NULL,
 label varchar(120) NOT NULL DEFAULT '',
 page integer,
 text text NOT NULL,
 answer text,
 difficulty smallint CHECK (difficulty BETWEEN 1 AND 3)
);
CREATE INDEX IF NOT EXISTS textbook_items_section_idx ON public.textbook_items(section_id, position);

CREATE TABLE IF NOT EXISTS public.topic_textbook_links (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
 section_id bigint NOT NULL REFERENCES public.textbook_sections(id) ON DELETE CASCADE,
 status varchar(12) NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested', 'confirmed')),
 source varchar(12) NOT NULL DEFAULT 'match',
 role varchar(12) NOT NULL DEFAULT 'primary',
 score real,
 confirmed_by_profile_id integer,
 confirmed_at timestamptz,
 UNIQUE (topic_id, section_id)
);
CREATE INDEX IF NOT EXISTS topic_textbook_links_topic_idx ON public.topic_textbook_links(topic_id, status);

-- Доступ только у бэкенда (service_role): тексты учебников ученикам напрямую не отдаются.
DO $$
DECLARE t text;
BEGIN
 FOREACH t IN ARRAY ARRAY['textbooks', 'textbook_pages', 'textbook_sections', 'textbook_items', 'topic_textbook_links'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated', t);
  EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
  EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE public.%I TO service_role', t || '_id_seq');
 END LOOP;
END $$;
